FROM wordpress:latest

# Configuración de entorno para conectar a la base de datos
ENV WORDPRESS_DB_HOST=dpg-cu5vfk5svqrc738dsktg-a
ENV WORDPRESS_DB_USER=wordpress_db_iwyw_user
ENV WORDPRESS_DB_PASSWORD=aiyUTq0BTDKMWRWSEqMFIubkx7t4iUm9
ENV WORDPRESS_DB_NAME=wordpress-db
EXPOSE 80
